### ISSUE TITLE
Client doesn't work with latest release of Clickhouse: 20.9.2.20

### ISSUE THREAD

**Issue by eranmiz132** [crobox/clickhouse-scala-client#109]
**Code**
  val config: Config
  val client: ClickhouseClient = new ClickhouseClient(Option(config))

  client.query("SELECT 1").map(result => print(result))

The above code is working with version: 20.3.12.112

**Got the following Exception:**

09:30:43,800 INFO  [ClickhouseClient] Starting Clickhouse Client connecting to SingleHostBalancer(http://localhost:8123)
09:30:44,979 WARN  [ClickhouseClient] Query execution exception while executing idempotent query, retries left: 3
com.crobox.clickhouse.ClickhouseException: Server [http://localhost:8123] returned code 404 Not Found; Code: 115, e.displayText() = DB::Exception: Unknown setting profile (version 20.9.2.20 (official build))
, query SELECT 1
	at com.crobox.clickhouse.internal.ClickhouseResponseParser.$anonfun$processClickhouseResponse$4(ClickhouseResponseParser.scala:51)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
09:30:45,000 WARN  [ClickhouseClient] Query execution exception while executing idempotent query, retries left: 2

**Comment by lwolters** [comment]
Hi Eranmiz132,

I'll look into this week. Keep you informed

**Comment by lwolters** [comment]
Hi Eranmiz132,

We've release version 0.9.13 today which should solve the issue. 

Closing this issue

**Comment by lwolters** [comment]
Hi Eranmiz,

Just following up; did you notice we released a new version that fixed the
issue?

Happy to provide any follow up,

Leonard

**Comment by eranmiz132** [comment]
Yes.

Thanks Leonard !

**Comment by Blackmorse** [comment]
Hi, @eranmiz132 
I have the same error now
Clickhouse version: 20.11.4.13
crobox version: 0.9.19

**Comment by lwolters** [comment]
Hi,

Could you please sent me a more detailed report of your error / exception?
I'm running it locally with this latest version and doesn;'t have any error
/ exception.

Looking forward to your reply,

Leonard

**Comment by Blackmorse** [comment]
`Source.single(Insert("akka_hattrick.t1", "{\"a\": \"a\"}")).toMat(sink)(Keep.right).run().onComplete(println)`

onComplete have an ClickhouseIndexingException and It's cause is:
```
com.crobox.clickhouse.ClickhouseException: Server [http://localhost:8123] returned code 404 Not Found; Code: 115, e.displayText() = DB::Exception: Unknown setting profile (version 20.11.4.13 (official build))
, query INSERT INTO akka_hattrick.t1 FORMAT JSONEachRow
```

**Comment by lwolters** [comment]
HI Andrew,

Thanks for your quick response. It looks like -somewhere- a configuration
file contains outdated settings. Could you please check the reference.conf
-or application.conf- used?
The default one contained in the project, i.e. reference.conf, doesn't
contain the <b>profile</b> setting anymore.

Could you please double check your local configuration files for the
following setting:

crobox.clickhouse.client.settings.profile

If available, simply remove it. It's not being used anymore.

L.

**Comment by Blackmorse** [comment]
@lwolters , 
Yes, profile settings was there, that's was a cause of the problems
Thanks a lot for your help.
