### ISSUE TITLE
Not sure how to use the client

### ISSUE THREAD

**Issue by k3rnL** [crobox/clickhouse-scala-client#137]
Hello,

I tried to copy paste the example from the readme, but it turns out that it's not enough.
I hardly suggest to update the doc and put at least one fully working example.

Right now, I'am able to run the program, but nothing special happens, it seems that some thread are hanging as the program does not exit at end of main:

```
val config: Config = ConfigFactory.parseString(
    """
      |crobox.clickhouse.client {
      |    connection: {
      |        type = "single-host",
      |        host = "localhost",
      |        port = 8123
      |    }
      |    maximum-frame-length = 100000
      |    retries = 3
      |}
      |""".stripMargin)
      
  implicit val ec: scala.concurrent.ExecutionContext = scala.concurrent.ExecutionContext.global

  val client = new ClickhouseClient(Some(config))
  client.query("SEECT 1 + 1").map(result => {
    println(s"Got query result $result")
  })
  ```

This code don't print anything

**Comment by lwolters** [comment]
Hi k3rnL.

Thanks for reaching out to us. Running your example, i clearly see the following stacktrace:

09:53:45.200 [ScalaTest-run-running-ClickhouseClientTest2] INFO com.crobox.clickhouse.ClickhouseClient - Starting Clickhouse Client connecting to SingleHostBalancer(http://localhost:8123)
09:53:45.215 [ScalaTest-run-running-ClickhouseClientTest2] ERROR com.crobox.clickhouse.ClickhouseClient - Can't determine Clickhouse Server Version. Falling back to: ClickhouseServerVersion(List(21, 8, 14)). Error: String: 2: **No configuration setting found for key 'settings'**
com.typesafe.config.ConfigException$Missing: String: 2: No configuration setting found for key 'settings'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at com.crobox.clickhouse.internal.QuerySettings.withFallback(QuerySettings.scala:38)
	at com.crobox.clickhouse.internal.ClickhouseQueryBuilder.toRequest(ClickhouseQueryBuilder.scala:28)
	at com.crobox.clickhouse.internal.ClickhouseQueryBuilder.toRequest$(ClickhouseQueryBuilder.scala:23)
	at com.crobox.clickhouse.ClickhouseClient.toRequest(ClickhouseClient.scala:23)
	at com.crobox.clickhouse.internal.ClickHouseExecutor.$anonfun$executeRequestInternal$3(ClickHouseExecutor.scala:117)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

I think this has to be with the way you're loading the config; not sure if the default client config (containing all defaults) is loaded correctly when you use the 'parseString' method

**Comment by k3rnL** [comment]
Ohh okay, you load your default conf like this, but Akka also is doing so. I understand now.
I'm not used to use Hooch like this. Usually I default the conf using "withFallback" to ensure that where ever the conf come from, I have the default values.

Anyway, my conf object seems fine now, I didn't get your exception, but just in case I fixed this. 
But the program is still hanging.
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/3842254/168401321-28fce9a9-2cce-4dc2-8023-2cd072be3b72.png">

**Comment by sjoerdmulder** [comment]
Both halves of this are now addressed, so closing — but you were right on both counts, and it took until 1.3.0 to fix.

**The README example didn't compile.** It showed `new ClickhouseClient(config, queryDatabase)` with an injected `implicit ActorSystem`. Neither exists: the constructor is `ClickhouseClient(configuration: Option[Config], customConnectionContext: Option[HttpsConnectionContext])`, and the client builds its own `ActorSystem` rather than taking one. The indexer example was also wrong — it used the deprecated `insertSink` with `Source` and `Sink` the wrong way round. Both rewritten in 1.3.0.

**The hang at end of main was the ActorSystem.** The client creates and owns one, named `clickhouse-client`, so nothing exits until you call `client.shutdown()`. That is now stated explicitly in the README's quick setup rather than left to be discovered.

The README also claimed Scala 2.12 support and pinned version `0.9.0`, both years stale; it now reflects the actual 2.13 + 3.3 cross-build.

Remaining gap, which this issue was also fair about: DSL documentation still lives in the wiki rather than the README. That is worth improving separately.
